apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: readings-output
spec:
  type: bindings.azure.eventhubs
  metadata:
    - name: connectionString
      value: Endpoint=sb://<EVENT HUBS NAME>.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=<EVENTHUBS KEY>;EntityPath=<EVENTHUBS ENTITY NAME>
